### ISSUE TITLE
Fuel cycle emissions issue

### ISSUE THREAD

**Issue by smasnadi** [arbrandt/OPGEE#146]
In Fuel Specs sheet cell C390, why NG fuel cycle emissions is higher than coal?

**Comment by qlangfitt** [comment]
I'd guess that table is showing the upstream emissions from mining/transporting coal vs. producing/processing/transporting natural gas, but not including combustion of the fuel. The reason I think this is that those numbers are referenced in the feedstock emissions columns on the Electricity Gen and Imports sheet. Coal-generated electricity has a higher overall CI because the inefficiency of combustion relative to natural gas. 

However, I think this brings up a good point for an easy improvement. Since it's not very clear what some of the tables on Fuel Specs and Fuel Cycle mean, could a brief (1 or 2 sentence) description be added to a few of them, similar to the description below Fuel Specs Table 4.2? Specifically the tables I think this would be useful for are Fuel Specs Table 4.3 and Fuel Cycle Tables 2.2, 2.3, 2.4, and 2.5.

**Comment by arbrandt** [comment]
Quinn is right. Explanatory note is added. In GREET terminology, the "Feedstock" column represents the emissions/energy associated with pulling the raw material from the environment, while the "Fuel" column represents the emissions/energy from making it into fuel. I added a note that explains this in more detail and uses the NG vs. coal as an example.
