### ISSUE TITLE
LHV/HHV - only for CI denominator or also calculation sheets?

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#152]
There are many places in the model that use heating value of gas or oil. The model allows switching between LHV and HHV on the Inputs sheet. That seems to mostly flow onto the Energy Summary sheet to go into the denominator of the CI calculation. However, there are few places where the LHV/HHV selection plays into calculation sheets. Should it be going into calculation sheets? If so, why do most sheets pulling gas heating value use a static LHV (from Fuel Specs tables 3.2 and 3.4)? The following respond to LHV/HHV:

**Gas Heating Value**
- Acid Gas Removal (L313)

**Oil Heating Value**
- Crude Oil Transport (M98:M102, M111)
- LNG Transport (M86:M90, M99)
- Drilling and Development (B78, M18)
- Exploration (M8)

**Comment by arbrandt** [comment]
Rationalized treatment of HHV LHV throughout. Issues fixed:
- Removed antiquated Schmidt fuel oil manual LHV table and replaced with API correlations for heating value LHV and HHV
- Ensured that all internal consumption within the model is done on LHV basis (pretty much the case before, but checked all drivers etc.). This is needed because all of the combustion EFs and derived quantities from GREET are in LHV basis. All energy consumption by process units is tracked as LHVs.
- Ensured that the energy summary sheet can pull either LHV or HHV to compute total energy outputs (primary and primary+secondary).
- The input sheet control ONLY controls what unit of energy output is used for the denominator of the end reported CI. I.e.., is it reporting gCO2/MJ LHV (default) or HHV.

**Comment by arbrandt** [comment]
Another quick pass to make sure everything was LHV basis on back sheets. Small correction to drilling and development required.
