### ISSUE TITLE
Oil sands default question based only on whether in Canada

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#163]
On _Secondary Inputs_, steam generation, "Use Canadian defaults for oil sands projects" (N257) is based on whether or not the country is Canada. Perhaps I'm looking at it wrong, but this is different than how I interpret the intent of that input. To me, the answer should be based on whether the project is oil sands or not, not on whether it is in Canada or not. If we only want to use those defaults for oil sands projects in Canada, I think the IF statement should be added to check that one of the oil sands options is turned on, since I believe there are fields in Canada that are not oil sands.

**Comment by smasnadi** [comment]
I modified cell N257. 
Yulia: please double-check

**Comment by yuliachen** [comment]
I agree that "Canadian default" is not a rigorous way of finding the right default value. However, as the primary input sheet does not include the option of choosing "steam injection type" but only allows for country specification, it is more reasonable to assume that the steam injection type (cell N258) default changes based on location (cell N257) rather than having location change based on injection type.

**Comment by smasnadi** [comment]
Yulia: Thank you for your comment. So I modified the default to cover the Canada condition as well as making sure that if the field is Canadian, it is oilsands as well.
