### ISSUE TITLE
Some emissions from gas transportation allocated to oil

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#185]
This issue has popped up a couple of times in specific contexts, but it's really an overarching issue that we probably need to think holistically on and adjust. OPGEE 2.0 doesn't include transmission and distribution of gas, but 3.0 does. Therefore, because OPGEE allocates all calculated emissions to all of the products by energy content, the new version of OPGEE should increase the CI of oil by allocating gas T&D emissions to oil. LCA guidance is pretty clear that when unit processes can be attributed to a specific product, those emissions should be not allocated across other products, and common sense dictates that gas T&D emissions have little to do with the crude oil product. Therefore, there are really only two options I can think of to address this. I had originally thought option 1 would suffice, but upon further reflection only option 2 accurately models the system.

1. When analyzing oil, use the "field" system boundary for gas and "refinery" system boundary for oil. Conversely, when analyzing for gas, use the "distribution" system boundary for gas and "field" system boundary for oil. This would prevent the primary product from taking on emissions from the secondary product beyond the field boundary, but actually would underestimate emissions overall. This is especially true when analyzing gas since some of the emissions from transmission and distribution would be inappropriately allocated to the oil (except that those processes would be cut out of the analysis when oil is the primary product, so in the end those emissions are never accounted for anywhere).

2. Rather than using an energy allocation for all emissions, only use the allocation for processes that actually act on multiple product systems. For processes acting on only one product system, just assign all emissions from that process to that product system. For example, downhole pump and separation are allocated across all products, but gas transmission is fully applied to the gas system. It would be ideal if there were a table somewhere that controlled which processes are allocated to each product, but might not be practical at this time. Instead, I think it would be acceptable to allocate only at the resolution of life cycle stage. An easy way to do this would be using the Active Field sheet. For allocated life cycle stages, nothing would change. For non-allocated life cycle stages, remove the energy summary ratio and add an IF statement to check the primary product.  Surface processing is the biggest sticking point of not going down to unit process level, but we might be able to settle for that to just be allocated (for now - maybe a future version could add a way to control by every process or could potentially solve this by breaking surface processing into substages for gas processing and oil processing).

**Comment by qlangfitt** [comment]
Again, at this point individual process level control is probably too complex, but an interesting reference for this is Table 4 of Zavala-Araiza et al. (2015) "Allocating Methane Emissions to Natural Gas and Oil Production".

**Comment by arbrandt** [comment]
Agree that this is a big issue. I have partly addressed it by method 1 above by adding an error flag to the system boundary in reference to an earlier issue. Therefore, the user is now directed to use field boundary for the secondary product stream. Agree that this should really be done at the process unit level for highest accuracy.

**Comment by qlangfitt** [comment]
I'm still a bit concerned going with method 1 for natural gas. I know most of the emissions will generally be from production, not from T&D, but it's not totally insignificant. I still find it off-putting to be allocating T&D emissions away when analyzing for natural gas (thereby artificially reducing the CI of gas and the total emissions accounted for if one were to separately analyze and add the emissions from oil and from gas for a particular field).

I'm not sure it's that heavy a lift to just adjust only the transport and distribution equations on the Active Field sheet to solve this problem. Unless I'm missing something, it seems as easy as simply changing cells G213:G214 and G220:G221. My suggestion is to replace the denominator of total energy produced ('Energy Summary'!F118) with the energy of the primary product ('Energy Summary'!F111). I think this should work for "crude transport", which is really crude and gas transport, because the numerator of that figure already adjusts to the system boundary, so the already implemented solution of cutting the secondary product at the field level excludes those emissions. For gas distribution, this figure only ever includes gas emissions. Would need to add a check to zero out the whole cell for G220:G221 if the denominator is 0, since that would result in an error.

Perhaps I'm missing that this change would mess up something else in the model or doesn't actually solve the problem accurately?

**Comment by arbrandt** [comment]
Hi Quinn,

Let me look this over in next day or two. Middle of the night here in Abu Dhabi and starting 20 hours of travel back home.

Adam

On Feb 11, 2020, at 9:52 PM, qlangfitt <notifications@github.com> wrote:

﻿

I'm still a bit concerned going with method 1 for natural gas. I know most of the emissions will generally be from production, not from T&D, but it's not totally insignificant. I still find it off-putting to be allocating T&D emissions away when analyzing for natural gas (thereby artificially reducing the CI of gas and the total emissions accounted for if one were to separately analyze and add the emissions from oil and from gas for a particular field).

I'm not sure it's that heavy a lift to just adjust only the transport and distribution equations on the Active Field sheet to solve this problem. Unless I'm missing something, it seems as easy as simply changing cells G213:G214 and G220:G221. My suggestion is to replace the denominator of total energy produced ('Energy Summary'!F118) with the energy of the primary product ('Energy Summary'!F111). I think this should work for "crude transport", which is really crude and gas transport, because the numerator of that figure already adjusts to the system boundary, so the already implemented solution of cutting the secondary product at the field level excludes those emissions. For gas distribution, this figure only ever includes gas emissions. Would need to add a check to zero out the whole cell for G220:G221 if the denominator is 0, since that would result in an error.

Perhaps I'm missing that this change would mess up something else in the model or doesn't actually solve the problem accurately?

**Comment by qlangfitt** [comment]
Sounds good. Safe travels on the long trip home!

**Comment by qlangfitt** [comment]
With the new GHG Summary sheet that is separated by process, this should be a mostly trivial task. I recommend adding IF statements to the block of transport and storage processes (GHG Summary H69:M76) as needed to only record GHG emissions for the appropriate processes. For example, for "Crude oil transport" (row 69) only draw in the emissions if the primary product is Oil. For gas transmission, only draw in the emissions when the primary product is gas.

Then, on the active field sheet, only divide the transport figures by the energy of the primary product (Energy Summary F121). I think this should work fine even if displacement is used since there is only 1 product and no need for displacement in the transport system portion of the model.

Same thing should be done for gas distribution. Not sure about LNG.

I think all other life cycle stages can remain as is, spreading across all products using allocation based on energy content of exported products since those stages all contribute emissions to both product systems and allocation should rightly be performed based on final disposition of the energy products.

**Comment by arbrandt** [comment]
Now fixed as of Apr 25th 2021 or so.
