### ISSUE TITLE
Possible error with offsite emissions credit/debit?

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#196]
When CO2 flooding is turned on, the GHG Summary sheet calculates various parameters regarding the CO2 balance from flooding and CCS. The "Summary offsite emissions credit" (row 58) is calculated for imports and exports. Each draws their values from the imports/exports table above, which correctly feeds negative or positive values. However, both also grab the "CO2 emitted during drilling and production of purpose-drilled anthropogenic CO2". I'm unsure exactly what that is, and perhaps it could be part of the imports (if so, should the row above also be included - CO2 emitted from work of separation and injection?), but currently it's added onto both imports and exports with the same sign (positive). This leads to a large offsite emission debit on the Active Field sheet for fields with CO2 flooding.

**Comment by smasnadi** [comment]
- Cell G42 of GHG Summary sheet most likely estimates the fuel cycle emissions associated with the CO2 that is used during the drilling process for CO2-EOR (Am I right, Adam?)
- I do agree with @qlangfitt that this emission should only be accounted in the imports cell (i.e., cell G58)

- @arbrandt: We both think that G42 should not be added in cell H58 (exports). What do you think? (I fixed the CO2-EOR issue #214 and if you check this, we should be done with CO2 related issues for now).
 
- @qlangfitt: I think Cell G41 (CO2 emitted from work of separation and injection) should not be included in offsite emissions credit/debit table due to the fact that those offsite emissions (e.g. fuel cycle of natural gas burnt in Gas Flooding Compressor) should be already accounted in indirect GHG emissions Table.

**Comment by qlangfitt** [comment]
I agree on all counts. I see now that G41 is accounted elsewhere.

**Comment by smasnadi** [comment]
Adam confirmed that G42 should NOT be included in Exports (H58). I fixed it.
