### ISSUE TITLE
Some California LCFS fields end up in infinite loop

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#202]
I'm running the largest LCFS fields to compare oil CI from OPGEE 2.0 to 3.0. Some of the field inputs from California LCFS put OPGEE in seemingly an infinite loop (two such field inputs attached). When I break the loop, it's usually trying to calculate steam enthalpy or sometimes solution gas oil ratio. Also, can see from the active field sheet that productivity index is blank. Looking through calculation sheets, it seems that the issues stem from steam generation, but it doesn't help to turn steam injection flooding off. 

I have figured out that increasing the GOR will allow the field to run through the VBA, but I have no idea why, ~~and there are still problems because the mass balances are way off~~. For example, increase Midway-Sunset's GOR to 350 or Kern River's to 400 and they run. _EDIT: Mass balance problem was a separate issue with our inputs, with Kern River having gas processing path 6 without CO2 gas flooding_

Also, curiously, this is only a problem when using the component fugitives approach. The site and depreciated fugitives approaches have no problem.

[LCFS Fields Failing to Run 3-10-20.xlsx](https://github.com/arbrandt/OPGEE/files/4314674/LCFS.Fields.Failing.to.Run.3-10-20.xlsx)

**Comment by qlangfitt** [comment]
I've found additional LCFS fields with this same problem, so it's important to figure out why this is happening.

**Comment by qlangfitt** [comment]
I've made a bit of progress. The step that the VBA is getting caught up in is at the start of the equipment loop in the fugitives VBA code (Module 1). The code calls Application.CalculateFull (Line 105) but it then gets caught up in steam tables on each iteration. It's possible the whole model would run if I gave it enough time, but I haven't tested that. If that line is commented out the model runs fine, but I assume it's there for a reason and can't just be disregarded like this. Hopefully this gets you a lead on tracking it down.

**Comment by arbrandt** [comment]
Jeff, this looks like it is in your domain.

**Comment by JSRuthe** [comment]
Figure it out - This is happening because Midway Sunset and Kern river have **extremely** low gas well productivities of 1.43 and 0.07 mscf/well/day. The US average for associated gas wells is 91 !!!

In the fugitives component-level calculator there is an "if statement" that checks to make sure total supply chain leaks (amortized over all wells) don't exceed the per well productivity. If they do, then the code loops back and "re-draws" leaks. Because these two fields have such low well productivities, it is hard to draw a leak set that doesn't exceed total gas production.

I'll need to think of an alternative check that doesn't bog down the model so much for these heavy oil fields

**Comment by JSRuthe** [comment]
@qlangfitt can you try running these fields again with the updated model and verify that we aren't running into an infinite loop? I have a feeling this should be fixed

**Comment by qlangfitt** [comment]
Tested and it is fixed.
