### ISSUE TITLE
Inconsistency between Active Field column K "default" and column N "deterministic default"

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#205]
On the Active Field sheet there is a column for the "Default" inputs (Column K) and another for the the "Dermin. default" inputs (Column N). In most cases, these are the same, but in many the values or formulas differ. It appears that the model uses the Deterministic Default to fill in blanks, but this is potential confusing. I know that some of the VBA code sometimes pulls from the "Default" column for individual adjustments (e.g., stabilizer) so should they be set to be identical to the Deterministic Default? I wonder if some of the blank deterministic defaults should actually contain the equation from the default.

Below are the inputs where these columns differ:
- Gas_flooding_01
- Oil_prod
- Num_prod_well
- Num_water_inj_wells
- Res_temp
- GOR
- WOR
- SOR
- Fraction_elec_onsite
- Fraction_steam_solar
- Heater_treater
- Stabilizer (but this one is adjusted in the macro to match the "Default" column)
- Fraction_diluent (this one also adjusted in macro to "Default")
- All ecosystem richness and land disturbance inputs
- Oil_transport_distance_tanker

**Comment by smasnadi** [comment]
Column N missing contents are transferred to column K.
Column K is re-named as Determin. default. 
Column N is removed from the uncert. table.

**Comment by qlangfitt** [comment]
Hi @smasnadi - just wanted to loop back around on this one. So it looks like for most of the inputs that differed between the two columns you stuck with the values that originally in Column K (all except gas_flooding_01 and oil_prod). However, the model used to reference Column N for what it actually filled blanks with. I think this means a lot of the actual smart defaults are now different than they used to be. Just wanted to double check that that was intended and which ones to leave as Column K values were carefully thought out and match with the defaults in the documentation (if that's described in the documentation). Thanks!

**Comment by smasnadi** [comment]
Thanks for the comment. Yes, most of col. K defaults were correct. I checked all cells one-by-one and modified defaults based on what I personally developed for OPGEE defaults in the Science paper based on global dataset statistical analysis. These defaults are mapped in the Documentation as well. The discrepancy of some columns are due to using old defaults for some cells. From the list you provided:

- Gas_flooding_01: cannot see any difference between col. N and K. both are set to 0.
Oil_prod: col. N was correct, so col. K is updated. 
Num_prod_well: An average productivity of 87.5 bbl/well-d is assumed as default well
productivity in OPGEE (from documentation). 
Num_water_inj_wells: see Table 4.2 of documentation 
Res_temp: = 70+1.8*J62/100 is correct based on documentation
GOR: defaults are updated based on more comprehensive data (see section 4.3.12)
WOR: see fig. 4.12 of documentation. 
SOR: both K and N were set to SOR=3
Fraction_elec_onsite: it is arbitrary to set this value 0 or 0.5 (or any other number) for onshore fields. My intuition says that most of onshore fields don't generate elec. onsite. We can modify this if we have any reference/data.  
Fraction_steam_solar: 0 unless determined. As far as I know, only few fields in Oman and Calif do solar.
Heater_treater: col. K default is there for a long time. I stick to it cause it look more rigorous than N! Should ask Adam what the basis is.
Stabilizer (but this one is adjusted in the macro to match the "Default" column)
Fraction_diluent (this one also adjusted in macro to "Default")
All ecosystem richness and land disturbance inputs: what we have there right now makes sense based on onshore/offshore condition.
Oil_transport_distance_tanker: the transport data is updated based on ave. data we have in OCI phase 2. 

Please let me know if you see any issue.

**Comment by qlangfitt** [comment]
Thank you! This all looks great.
