### ISSUE TITLE
Check on source for default gas composition

### ISSUE THREAD

**Issue by arbrandt** [arbrandt/OPGEE#207]
Where does default gas composition come from. Why 6% CO2?

**Comment by smasnadi** [comment]
From OPGEE documentation (since OPGEE V.1):
<img width="605" alt="Screen Shot 2020-03-18 at 23 12 11" src="https://user-images.githubusercontent.com/46761921/77029052-0687b780-6971-11ea-8923-a964a054e126.png">
<img width="621" alt="Screen Shot 2020-03-18 at 23 13 01" src="https://user-images.githubusercontent.com/46761921/77029053-07204e00-6971-11ea-96d3-b315d9e661b2.png">
