### ISSUE TITLE
Active field final GHG result does not match Results sheet GHG result

### ISSUE THREAD

**Issue by smasnadi** [arbrandt/OPGEE#210]
Why active field final GHG result (gCO2eq/MJ) is NOT the same as Result sheet GHG result? I noticed this now and also when I was running 9000 global fields in 3.0 few months ago.

**Comment by JSRuthe** [comment]
It looks like this issue only occurs when MC runs > 1.

I suspect this is another issue with updating when parameters are randomized

**Comment by JSRuthe** [comment]
So I traced this error to differences in VF emissions for production and surface processing segments.

I actually don't think this is an "error". The reason we see differences are because the Results sheet contains copied "values" while Active Field sheet contains "active formulas". Because at the end of the macro we reset the sheet to automatic (formula updating), the active formulas on the Active Field sheet have the chance to update (e.g., redraw random leakage volumes). Hence the difference with the copied values on the Results sheet.

Therefore, I don't see any problem with this. If everyone (cc @qlangfitt , @smasnadi , @arbrandt ) is ok with this I will close this issue

**Comment by qlangfitt** [comment]
Jeff, I agree. I had noticed an issue with Results and Active Field in disagreement for deterministic runs a couple weeks back (see issue #204), which is a problem. But Adam fixed that and if it is only occurring with uncertainty runs enabled due to a new set of random draws, then I don't see a problem with that.

@smasnadi - you're not seeing this on deterministic mode right (uncertainty runs = 1)? Or if so, is the version you were seeing it on more than about a week old?

**Comment by smasnadi** [comment]
@qlangfitt : You are right. Just double-checked and can confirm that for deterministic mode the values in results and active field sheets match.

**Comment by arbrandt** [comment]
Sounds like this is resolved! Closing the issue.
