### ISSUE TITLE
Site method division of emissions by site equipment

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#218]
For both production and processing fugitives in the Site method, the emissions are divided between processes by pre-defined assumed breakdowns. Wondering why these breakdowns assign no emissions to the stabilizer, fractionation, or Ryan Holmes? Wouldn't it make more sense to assign some of the emissions to each process (perhaps by the breakdown seen in your big fugitives study?) so that fields would see differences in fugitive emissions based on how much equipment the gas is running through? Maybe I'm thinking about it wrong, but wanted to throw out the suggestion.

**Comment by arbrandt** [comment]
The challenge with site methods is that they measure downwind plumes and so don't give info about the contributions from each piece of equipment (unlike component level method).
 
Here we "back assign" the site level emissions to equipment because OPGEE wants process unit level flows for the mass balance and flow sheet. Any method to do this assignment would be imperfect, of course. 

I think assigning site-level emissions to process units that might not exist on a site is challenging. Since we know that wellheads and separators exist on all sites, because they are the two most basic process units, I chose those. For now, let us keep site level emissions divided between those units. Since we will be defaulting to the component emissions method, this won't be an issue in most cases.
