### ISSUE TITLE
Production bins in site fugitives method

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#219]
In the Site fugitives method, the production emissions are calculated based on which bin the site-level production rate falls in. On the other hand, the processing emissions are based on a regression equation. I see that a regression equation was calculated for production emissions, but not used in the model's calculations. Although I see the value of sticking with the current approach for uncertainty mode, I think that the regression equation should be used for the deterministic default for two reasons. First, the hard bin cutoffs seem to be potentially exploitable or at least could cause large jumps in results based on small errors in input data if a field is near a bin cutoff. Second, some of the bins (notably bin 3) appear to violate the overall trend that higher site-level production leads to lower percent leak rates. Isn't it likely that this is not a real effect, but rather the result of sampling real-world data with variability? If so, it seems like using the regression that models the overall smoothed out behavior would be more robust. Is there is a reason to stick with the bins over using the regression for the deterministic value (such as what happens on the very low or very high end)?

**Comment by JSRuthe** [comment]
The regression equation from Omara shouldn't be used because it underestimates compared to both Alvarez and the non-parametric bootstrapping model (see Fig 4b in Omara et al 2018).

However, this should no longer be an issue. In our new approach, we calculate a segmented productivity distribution which should reduce the effect of bin cutoffs.
