### ISSUE TITLE
On-site electricity generation emissions not included in overall CI

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#229]
I was investigating the relationship between fraction of onsite electricity generation and total emissions and noticed an unexpected negative trend (more onsite gen=lower CI). Tracing it back, the emissions from onsite non-cogen electricity generation are calculated on the GHG Summary sheet (H18), but it doesn't appear that those emissions are carried onto the Active Field sheet anywhere, so they don't contribute to the CI. Essentially, electricity generated onsite (non-cogen) seems to be considered emissions-free. Let me know if I'm just missing something intricate about how those emissions are handled.

**Comment by arbrandt** [comment]
Just checked into this by tracing dependents from GHG summary sheet of the electricity generation emissions. This was indeed causing a problem, in that those cells were never incorporated into the active field emissions sub-terms. In order to avoid changing macros and potentially introducing additional bugs, the onsite electricity generation emissions and energy use are now added into the broad category "surface processing" for the active field sheet. Now the model is much less sensitive to whether electricity is generated onsite or not, which conforms with expectations. This also holds for cases where downhole pumps are electrified, which exhibited an even bigger delta.
