### ISSUE TITLE
Diluent adjustment factor calculation broken

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#247]
The diluent adjustment factor on the GHG Summary sheet (G56) points to blank cells on the Heavy Oil Dilution sheet. Older versions of OPGEE 3.0 show which cells these should refer to, but the Heavy Oil Dilution sheet was changed at some point and the cell references broken.

Should be:
1-frac_diluent*LHV_diluent/(frac_diluent*LHV_diluent+(1-frac_diluent)*LHV_bitumen+(1-frac_diluent)*LHV_heavy_oil)

Also, be careful not to double count bitumen and heavy oil in the denominator. Should be one or the other depending on the type of heavy oil processing (I believe).

**Comment by arbrandt** [comment]
I believe I was able to fix this. There were actually a few issues with the formula. Now it gives 1 if the crude is conventional (dilution factor is 0) or upgraded. If it is diluted, it takes the volume fraction of diluent times the energy denisty of diluent, normalized by the energy content of the diluted bbl, depending on whether you are diluting heavy crude oil bitumen. Tested with field 83.

**Comment by qlangfitt** [comment]
Maybe there's a reason I'm not seeing, but I don't understand why the diluent adjustment factor is set to be 1 for all oil sands fields. From what I can tell OPGEE 2.0 didn't treat oil sands this way and our definition of oil_prod for oil sands is the amount of undiluted bitumen.

**Comment by arbrandt** [comment]
This was a relic from a prior version. It used to be that no stand-alone mines diluted their bitumen for sale. They all sold it to merchant upgraders because the quality of separation at the mine was such that the sand/mineral fines entrained in the bitumen would cause problems at refineries. Newer technology, like that at the Kearl Mine, allows for direct dilution and sale of the bitumen. Numerous small fixes here to allow you to dilute bitumen and sell it from mines. See test columns 117 to 121, which I have changed to be diluted mined bitumen.
