### ISSUE TITLE
Demethanizer electricity use missing from gen and imports

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#249]
The demethanizer uses electricity for fans and can use electricity for compression. While this electricity is included in the Energy Summary sheet Table 1 and 2, it is left off of the Flow Sheet and Electricity Gen and Imports sheet. This results it is being left off of the  Energy Summary sheet Table 3 and therefore the CI calculations on the Active Field shet.

Need to add demethanizer electricity stream to Flow Sheet and Electricity Gen and Imports sheet.

**Comment by arbrandt** [comment]
Yikes! This was a big oversight. Now the problem should be fixed. Added: new flow 200 for electricity use by demethanizer. Added to electricity gen and imports summary sheet. Added to flow table. Added yellow arrow on process flow diagram. Only problem is that this flow 200 is out of order, coming numerically after the net imports. This could be fixed in a future version, but feel that best approach right now is to not renumber all of the flows. Impact to default field is about 0.15 gCO2/MJ that we were missing.
