### ISSUE TITLE
Off-site compressor fugitive emissions

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#258]
For many of the various compressors that are not considered on-site, the fugitive emissions are calculated very simply as a static emissions rate. As far as I can tell, for each compression process of this type (e.g., gas reinjection compressor, gas lifting compressor, etc.) the emissions are set at 29 kg CH4/d. There doesn't appear to be any adjustment for the quantity of gas flowing through or number of compressors - just a set mass flow rate of emissions if the process is used. That seems problematic for very large or very small fields that will either be far underestimating or far overestimating. Seems like it should be based on the number of compressors (which may be indirectly estimated from throughput of the process).

**Comment by JSRuthe** [comment]
see 9a57298
and 1d010f6

**Comment by qlangfitt** [comment]
This was fixed for gas reinjection compressor, but not for the other three compressor types that were relying on this methodology:

- Pre-membrane compressor
- Gas lifting compressor
- VRU compressor

**Comment by JSRuthe** [comment]
Returning to my previous classification (copied from a previously closed issue)

- Any equipment associated with enhanced oil recovery will be considered "off-pad". This will include compressors and wells used in sour gas, HC gas, and CO2 reinjection or flooding. Based on a quick scan of SPE literature (see, for example, here). spacing between production and injection wells is in the hundreds of meters
- Any equipment associated with gas lift is "on-pad" since the gas is injected through casing tubing of the producer well

Gas lifting and VRU are "on pad". Therefore, I assume that these are already contained in the site level calculator (downwind measurements will capture them) and component level calculator (will be included in compressor counts used to parameterize activity factors). Therefore fugitives for these sheets will be set to zero.

Pre-membrane compressor is considered off pad since it is associated with enhanced oil recovery. I will add a new fugitives stream connected to the new "VF Secondary production" sheet

**Comment by JSRuthe** [comment]
comments addressed with commit above
