### ISSUE TITLE
Mass balance issue in uncertainty mode persists 

### ISSUE THREAD

**Issue by JSRuthe** [arbrandt/OPGEE#262]
Related to issues #191 and #212 

See screenshot below (running Akpo, field 134, gas functional unit, 3 uncertainty realizations)

![image](https://user-images.githubusercontent.com/42356585/89918429-3f8e2600-dbb7-11ea-8121-8e39ff858036.png)

**Comment by qlangfitt** [comment]
For whatever reason, OPGEE doesn't work in uncertainty mode on my computer so couldn't replicate, but I see negative values for "Transport to market" and "To other stream". I actually get negative value even in deterministic mode and it derives from the demethanizer sheet. For this particular field, it seems to stem from the extremely low C2H6 composition on the input sheet. Basically, the regression equations calculate the expected C2 output as much higher than the amount of C2 coming into the process. Anyway, not sure if that's what causing the mass balance problem or if this is something completely separate.

**Comment by arbrandt** [comment]
I am able to recreate the error on the default field settings as well. The error is small in most cases, but there.

If I run field 0 (default) in 1 uncertainty realization mode, mass balance holds to 1.00000000 at least. If I run field 0 (default) in uncertainty mode with 2 realizations, mass balance terms are all close to zero, but slightly off in 1/100 or 1/1000 place. Spent some time staring at it tonight and can't find a reason... More digging and thinking....

**Comment by arbrandt** [comment]
Spent some more time looking into this. Observations:

It is not a component vs. site model issue. If in deterministic mode it does not occur for either. If in uncertainty mode, it occurs for both. This is true out to 10 decimal places.

The error amounts on RHS of flow sheet changes slightly with recalculation (force recalc using "ctrl ="). This is because it is drawing new fugitives values that are different.

Drawing a whole new set of fugitives values should not cause the problem. Because we know the math holds on the mass balance out to 10 decimal places in static mode, the same accounting should hold for any and all static draws of fugitives.

I think what is happening is a calculation refresh issue. Something is causing a recalc partway through (perhaps multiple times) that resets fugitives values to a different value partway through the big messy accounting. 

Let's table this for now.
