### ISSUE TITLE
Summary of offsite transmissions and storage fugitive emissions

### ISSUE THREAD

**Issue by JSRuthe** [arbrandt/OPGEE#267]
This issue combines issues #257 and #259. These issues both reference fugitive streams associated with offsite (off of well-pad) transmission and storage equipment.

Some time ago, @arbrandt and I elected to handle **all** off-site fugitive emissions using the site-level approach. Therefore, the user has the option of using the component-level model **or** the site-level model for on-site equipment, but **only** the site-level model can be used for off-site equipment (which includes gathering and boosting, transmissions and storage, and distribution infrastructure.

Loss-rate estimates from the Zimmerle et al. (2015) paper are applied to venting and fugitive emissions streams for transmission and storage. Zimmerle et al. is a modelling study fitted using data from Subramanian et al. (2015), who make measurements at 36 transmission compressor stations and 9 storage compressor stations. Unfortunately, the paper is unclear on exactly which equipment are measured (many are bundled within a category of "non-compressor component fugitives"). I've emailed Dan Zimmerle and learned that "non-compressor equipment" includes storage separators but does not include storage wellheads.

Based on this information, several emissions streams in OPGEE will need to be eliminated to avoid double counting with the transmission and storage loss rates (as these loss rates contain emissions from multiple equipment). These emissions streams are summarized in the Table below:

![image](https://user-images.githubusercontent.com/42356585/94491926-64118200-01a6-11eb-908d-4fd71fb6061d.png)

@arbrandt and @qlangfitt please comment on this approach. I'm not sure exactly how to handle storage wellheads as it is difficult to justify how many to allocate to single field. As a reference, there are ~3300 storage wells in the US (based on DrillingInfo), which seems very small compared to the total well count.

**Comment by qlangfitt** [comment]
Looks good. Storage wells are kind of strange because clearly it is not referencing the number of storage wells on an oil and gas field, but rather taking into account losses from them further down the natural gas supply chain. Therefore, seems like if any factor is used it should just be generic and apply equally to all exported gas. I can think of at least two options, one simple and one complicated. 

Simple option: Use the total storage wells emissions from the US EPA GHGI for 2018 (15.4 kt CH4) and divide by total US production to get a fractional leakage rate. Then just apply that fractional leakage rate to all exported gas. This would be like a population factor and we wouldn't have to guess what fraction of gas goes into storage or not (although maybe we're already accounting for that?).

Complicated option: Perhaps, if DrillingInfo has the "production" data for all US storage wells, we could just run those through OPGEE's component fugitives tools as if they were normal wellheads, get the gas-weighted average loss rate, and apply that loss rate to all gas that passes through storage (would have to assume a % of gas going through storage). My two cents is that this option is probably a lot of work, complexity, and assumptions for something that's likely to be a pretty small portion of total emissions.

**Comment by JSRuthe** [comment]
Great suggestions Quinn,

I'm also interested in ideas for how to deal with injection wells. This is within the production segment, so it could hypothetically be dealt with using my component-level model. However, a couple complicating factors:

- Are the measurements made at production wells necessarily comparable to leaks at injection wells? (the pressure gradient is into the reservoir, not out of the reservoir).
- Developing a loss rate according to the "well" distribution already located in the tool will be tricky. The distribution will need to adjusted to account for the relative number of injection wells and production wells (since there are a smaller number of injection wells, the emissions should be lower). 

I checked the GHGI and they unfortunately don't have a line item for leaks from injection wells. I was hoping there might be another "simple option" like we're considering above

**Comment by arbrandt** [comment]
Hey Jeff,

Should we catch up today? Can you zoom after lunch?

Adam

On Sep 28, 2020, at 7:35 PM, JSRuthe <notifications@github.com> wrote:

﻿

Great suggestions Quinn,

I'm also interested in ideas for how to deal with injection wells. This is within the production segment, so it could hypothetically be dealt with using my component-level model. However, a couple complicating factors:

  *   Are the measurements made at production wells necessarily comparable to leaks at injection wells? (the pressure gradient is into the reservoir, not out of the reservoir).
  *   Developing a loss rate according to the "well" distribution already located in the tool will be tricky. The distribution will need to adjusted to account for the relative number of injection wells and production wells (since there are a smaller number of injection wells, the emissions should be lower).

I checked the GHGI and they unfortunately don't have a line item for leaks from injection wells. I was hoping there might be another "simple option" like we're considering above

**Comment by JSRuthe** [comment]
see commit 1d010f6

**Comment by JSRuthe** [comment]
@arbrandt and @qlangfitt : In the latest commit I've finalized adjustments to venting and fugitives for off-site secondary projection methods. Off-site reinjection and associated compressors are now connected to a new sheet "VF - secondary production". This sheet contains averaged (not tranche-based) loss rate fractions from my model.

By using loss rate fractions we eliminate the need for number of injection wells (if we were using mass loss rate, then we would need to scale fugitive emissions according to the number of equipment), because the fugitive emissions will instead be scaled according to the volume of gas being injected (already taken care of by OPGEE).

This new feature has been tested on several oil fields employing these production practices
