### ISSUE TITLE
Offsite Emissions in Active Field in Cell AK19

### ISSUE THREAD

**Issue by myjabbar** [arbrandt/OPGEE#296]
This then relates to Cell **G117** in the GHG Summary sheet.

Suggestions @smasnadi 
 =(H85+G113*(H83+H84+H86+H87+H88)+H89+G109)
Do you think we can remove the addition of cell **G101** from the above equation?

Also, I am still not clear how the G109 helps in the CO2 balance from CO2 flooding and CCS table in the GHG Summary Sheet.

Thanks,

**Comment by smasnadi** [comment]
G101 of GHG summary is basically the amount of additional CO2 used during EOR drilling and processing out of GREET model. See cell F79 explanation for more details. It is per mmbtu gas produced, so the natural gas LHV is incorporated. Because the CO2 that is used for EOR drilling purpose come from outside of facility, it should be accounted as Imports. 

This CO2 is not the one injected during the process (fresh or recycled). It is an offsite CO2 coming from out of the facility. 

@arbrandt: am I right?

**Comment by smasnadi** [comment]
@myjabbar I created issue#301 to address your point.
