### ISSUE TITLE
Electricity Generation from Diesel Generators

### ISSUE THREAD

**Issue by LondonEng** [arbrandt/OPGEE#303]
Under the “Drivers” worksheet, there is a table used for forecasting energy intensity for a diesel engine. (Row 73). This is used to determine the energy intensity of the diesel engines in the facilities.

The formula for the energy intensity of a diesel engine is: (from worksheet “Electricity Gen and Imports” cell M101)

Energy Intensity = (-0.4299*BHP+7235.4)*(1/0.75)*(1/0.96)

You can see in the attached spreadsheet that as the bhp demands of the facilities go above 16,800 bhp, the system flips to negative. 

I noticed this because I am trying to model an existing offshore facility that has bhp demands that will increase in time from 14,000 to 20,000. As I was modelling each year I noted the emissions from electricity went negative.

Not sure of the best fix. It could be you need to divide power total power consumption by the maximum power output of a given generator, to figure out the average energy intensity of a single generator, and then multiply that by the number of generators needed. 

Thank you for your efforts on this.

[Energy Intensity Flaw OPGEE.xlsx](https://github.com/arbrandt/OPGEE/files/5538128/Energy.Intensity.Flaw.OPGEE.xlsx)

**Comment by smasnadi** [comment]
Thank you! 
@arbrandt @qlangfitt the Diesel engine energy consumption relationship is not scalable for super high bhp ( around >16900bhp related to offshore fields). 
- Should we put a condition to only use Table 1.3 relationship (Drivers sheet) for the rage of 0-3000 bhp?
- Any idea to what to do for much higher bhp values?

**Comment by qlangfitt** [comment]
I'd like to hear what Adam thinks, but my suggestion for an easy fix would be to use the correlation up to BHP=3000, and then have a static value for anything larger than that. If we can find technical data sheets for larger engines of this types, we could just set a typical efficiency for everything over 3000. If that's not available, what about just assuming that efficiency doesn't increase much after 3000 BHP and maxing out the efficiency at that point? The latter could be implemented with the following:

=1/0.96*IF(Generator_type=1,(HLOOKUP(M99,Drivers!C35:AE36,2,TRUE)),IF(Generator_type=2, (HLOOKUP(M99,Drivers!C66:AS67,2,TRUE)),IF(Generator_type=3,(MIN(M99,3000) * Drivers!K89+Drivers!K88),"ERROR")))*(1/0.75)

Of course, if we could find a bunch more data sheets for engines within the gap, we could just extend the regression instead.

**Comment by arbrandt** [comment]
That is what I was going to suggest. I haven’t seen efficiencies for larger engines, though perhaps we could search and find some.

Essentially, since these are efficiency factors, it would not assume constant energy consumption for larger engines, but constant efficiency. That seems reasonable.

On Nov 17, 2020, at 1:27 PM, qlangfitt <notifications@github.com> wrote:

﻿

I'd like to hear what Adam thinks, but my suggestion for an easy fix would be to use the correlation up to BHP=3000, and then have a static value for anything larger than that. If we can find technical data sheets for larger engines of this types, we could just set a typical efficiency for everything over 3000. If that's not available, what about just assuming that efficiency doesn't increase much after 3000 BHP and maxing out the efficiency at that point? The latter could be implemented with the following:

=1/0.96IF(Generator_type=1,(HLOOKUP(M99,Drivers!C35:AE36,2,TRUE)),IF(Generator_type=2, (HLOOKUP(M99,Drivers!C66:AS67,2,TRUE)),IF(Generator_type=3,(MIN(M99,3000) * Drivers!K89+Drivers!K88),"ERROR")))(1/0.75)

Of course, if we could find a bunch more data sheets for engines within the gap, we could just extend the regression instead.

**Comment by smasnadi** [comment]
@LondonEng Thanks for your replies. Cell M101 is modified as suggested by qlangfitt to keep the eff constant after 3000 bhp.
