### ISSUE TITLE
Errors on multiple Worksheets

### ISSUE THREAD

**Issue by parissamj** [arbrandt/OPGEE#305]
Errors in multiple worksheets:
[2020-09-Global Fields_OPGEE_V3.0a_BETA_mod..zip](https://github.com/arbrandt/OPGEE/files/5574924/2020-09-Global.Fields_OPGEE_V3.0a_BETA_mod.zip)

1. Sheet GHG Summary: M45
2. Sheet Crude Oil Dewatering: Cell Q20 and Q28 (Calculations for CH4 and total gas).
3. Sheet Gas Transmission Compressors: Cells O16, O22 to O23, and O28.
4. Sheet Fuel Gas Imports: Cells AC16, AC 20, AC21, AC28.

**Comment by arbrandt** [comment]
Hi Parissa, would help to break these out into separate issues so that we can assign them to folks and tackle them one by one. Also, some description of the error would help in understanding what needs to be done. Thanks for the debugging help!!!!

**Comment by arbrandt** [comment]
Line by line comments:

Sheet GHG Summary: M45

This is a strange one. It appeared to be strange that there was an error. I clicked in the cell and hit return, and error went away. Perhaps an issue with an iterative calculation that had not updated? Sometimes these issues arise.

Sheet Crude Oil Dewatering: Cell Q20 and Q28 (Calculations for CH4 and total gas).

Good catch. This is related to a fundamental issue that should be fixed in the next incarnation of OPGEE. We don't track combustion product exhaust streams, so we should not expect gas species mass balance. This should be fixed in a future version of OPGEE, but tabled for now. Will add this as a separate new issue and table it. Note added to the worksheet:


Mass balance will not hold for gases because of fuel gas consumed in dewatering is treated as an input but we don't track combustion products as an output.
--
Mass balance check removed here.


Sheet Gas Transmission Compressors: Cells O16, O22 to O23, and O28.

This was an issue where the gas transmission compressor was off, but gas was still coming in. Changed the mass balance checks to only look for mass balance when the unit is turned on.



Sheet Fuel Gas Imports: Cells AC16, AC 20, AC21, AC28.


Fixed. Sum on outputs side was missing last column.
