### ISSUE TITLE
Threshold for non-NG driven pneumatic controllers

### ISSUE THREAD

**Issue by JSRuthe** [arbrandt/OPGEE#330]
We are considering implementing a "smart" threshold for toggling NG driven pneumatics (default) to non-NG driven pneumatics based on high H2S content (where methane emissions would be set to zero).

According to the EPA, a sour gas has an H2S concentration of 24 ppm: https://www3.epa.gov/ttn/chief/ap42/ch05/final/c05s03.pdf

However, I have a feeling this should not be the theshold for a smart default. If so, the majority of basins in the US would not be using NG-driven pneumatics and we know this is not the case

Based on some material I've been reading from TCEQ, H2S is regulated at a certain non-zero threshold on a facility-level basis. I think in some "sour" basins, it might be possible that NG is used to power pneumatic controllers. https://www.tceq.texas.gov/assets/public/assistance/sblga/oil-gas/Air-Permitting-Options-for-OG-Industry-Presentation.pdf

I think this is more complicated, and should probably be handled on a case-by-case basis. Otherwise, perhaps setting the smart default at a threshold higher than the EPA sour gas definition

Does @qlangfitt know someone in CARB who we can speak to about this?

**Comment by arbrandt** [comment]
I have seen a range of numbers from 4 to 100 ppm for a defin of "sour", which I am sure varies by jurisdiction. What requirements there then are for sour is another question. Perhaps we set a default that is somewhat loose, and let folks tune it  tighter if they want. I don't want it to default to leaking gas if h2s is 2%, given that it is fatal at very low concentrations in air.

**Comment by arbrandt** [comment]
Looks like immediately fatal at 500-1000 ppm, respirtory problems between 10-500.

**Comment by JSRuthe** [comment]
Based on our discussion here I propose the following solution:
- A flexible sour gas definition (In Secondary Inputs). The default will be the [TCEQ definition](https://www.tceq.texas.gov/assistance/industry/oil-and-gas/sour-gas-handling-compliance#:~:text=TCEQ%20designates%20operations%20as%20sour,30%20TAC%20101.1(96)%20%5D) of 24 ppmv but the use can adjust.
 - A binary switch for non-NG pneumatic controllers (In Secondary Inputs). By default, non-NG pneumatic controllers will be switched on if gas is sour (by the definition above).

My main concern with this approach is that it will systematically underestimate emissions from pneumatic controllers if our defaults are not tuned properly. For example, our current default setting for H2S is 0.01% mole fraction, which works out to 100 ppmv. By default, all pneumatics will be set to non-NG.

I finally got around to playing with the USGS EGDB (Energy Geochemistry Database) (its in MS Access which I don't understand) and filtered "Natural Gas" records for H2S. Of the 13,722 valid NG records, only 54 have non-zero H2S. This works out to < 0.5% of sampled wells. 

I recommend setting the default H2S mole fraction to 0% so that a field is sour only if the user has information on H2S content.

**Comment by arbrandt** [comment]
Excellent detective work. Nice that we have some more support for H2S defaults.

I support these changes. Please implement.

On May 12, 2021, at 8:22 PM, JSRuthe ***@***.***> wrote:

﻿

Based on our discussion here I propose the following solution:

  *   A flexible sour gas definition (In Secondary Inputs). The default will be the TCEQ definition<https://www.tceq.texas.gov/assistance/industry/oil-and-gas/sour-gas-handling-compliance#:~:text=TCEQ%20designates%20operations%20as%20sour,30%20TAC%20101.1(96)%20%5D> of 24 ppmv but the use can adjust.
  *   A binary switch for non-NG pneumatic controllers (In Secondary Inputs). By default, non-NG pneumatic controllers will be switched on if gas is sour (by the definition above).

My main concern with this approach is that it will systematically underestimate emissions from pneumatic controllers if our defaults are not tuned properly. For example, our current default setting for H2S is 0.01% mole fraction, which works out to 100 ppmv. By default, all pneumatics will be set to non-NG.

I finally got around to playing with the USGS EGDB (Energy Geochemistry Database) (its in MS Access which I don't understand) and filtered "Natural Gas" records for H2S. Of the 13,722 valid NG records, only 54 have non-zero H2S. This works out to < 0.5% of sampled wells.

I recommend setting the default H2S mole fraction to 0% so that a field is sour only if the user has information on H2S content.

**Comment by JSRuthe** [comment]
Added!

If this looks ok to you @qlangfitt I'll close

**Comment by qlangfitt** [comment]
Sounds good to me.
