### ISSUE TITLE
CO2 mass balance error

### ISSUE THREAD

**Issue by myjabbar** [arbrandt/OPGEE#331]
CO2 mass balance error

In my opinion, the formula in cell LD14 in **Flow Sheet** to be replaced with 
= BA14 +BY14+CC14 +**CG14**

@smasnadi can you please confirm the above change

**Comment by smasnadi** [comment]
@myjabbar Thank you! 
I think you are referring to cell LD15 (CO2 injected stream). I think the way that mass balance is performed in Flow Sheet is to account for streams AFTER fugitives taken out from the stream, so that all fugitives can be summed up together (see cell LF15). Thus, if we want to add CG14 instead of CS14, then we need to modify LF15 because the amount of CO2 in stream 277 is already included in CG14. 
If you need that cell to reflect what you need for CO2-EOR, I would suggest to modify it in your local version. 
Will close this for now, but would be happy to re-open and discuss it further if needed.
