### ISSUE TITLE
Use of heavy oil upgrading varies between OPGEE 2.0 and 3.0

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#345]
In OPGEE 2.0, heavy oil upgrading occurs so long as an upgrader type (<>0) is chosen. The ON/OFF tag for heavy oil upgrading in OPGEE 3.0 follows the same convention, however, the volume of oil will be 0 unless the field is specified as an oil sands field. I am unsure of the proper behavior, or whether it's simply incompatible to select an upgrader type without being oil sands, but please clarify or fix this.

**Comment by arbrandt** [comment]
Fixed. Upgrader can be chosen for heavy oil produced from wellbore. The issue was that if the stabilizer was on, it would not go to the upgrader next because of the flow path. Have now issued an error check that flags a case where the stabilizer is on and the heavy oil upgrading is on. This makes sense as an error as the stabilizer is used for crude that is too volatile and gas rich, while upgrading is used for crudes that are too heavy.
