### ISSUE TITLE
Component VF method liquids unloadings for oil fields

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#368]
@JSRuthe @arbrandt - very important issue to solve before freezing (should be easy enough)

Liquids unloadings were recently added to the component VF method. Since these only apply to gas fields, there are now more columns in the gas field section than the oil field section under the "Equipment leaks" header. This is accounted for in the row identifier (cells D44:D53), but it not accounted for in the row adders anywhere on the sheet. This means that loss rates are getting pulled for the liquid unloading processes for oil fields (but for LU - plunger what's getting pulled is the loss rate for wells).

The problematic places I see are on the VF - component sheet are the following ranges:

- I42:V42
- I58:V58
- E74:G240
- B247:F260

This is an urgent issue to solve since it's basically double counting wellhead losses right now for oil fields. Let me know if this is confusing or if you have questions. I'm free to lend a hand if needed.

**Comment by JSRuthe** [comment]
Hmmm.. I thought I'd double checked this wasn't an issue in my validation exercises. I'll take a look at this right now

**Comment by JSRuthe** [comment]
Because there is a GOR check in the "Chosen value" field for LU (cells D36:37), methane from LU is not counted if you are modelling an oil field. This is why the calculation was still checking out in my validation exercises.

I can totally understand the confusion though. I'll add GOR checks to the cells you're referencing so that it doesn't look like any double counting is happening

**Comment by qlangfitt** [comment]
Ah yes I see what you're saying. Glad you already had it right in the chosen field. I was indeed just looking at the other columns and not realizing it was pinched off at that point.
