### ISSUE TITLE
Separator gas outlet pressure after boosting compressors issue

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#380]
If change the default value of M122 under the secondary inputs tab to 1000 psia, the excel model run will crush

**Comment by qlangfitt** [comment]
Tracked this down to the demethanizer inlet boosting compressor. By default, the demethanizer operates at 600 psi, so when the gas treatment stream is higher than that, the demethanizer inlet boosting compressor will calculate negative energy use. Simply need to set a floor of 0 in Demethanizer M58 and the problem is solved.

**Comment by arbrandt** [comment]
Set the value equal to the larger of: the calculated adiabatic work of compression value of 0.  So if it computes negative work, it is set equal to 0. Tested with m122 on SI set to 1000 and the model does not crash any longer.
