### ISSUE TITLE
Gas formation volume factor

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#385]
gas formation volume factor (Cell M57 under Well and downhole pump Tab) does not have the z_factor

**Comment by arbrandt** [comment]
Fixed. Because z-factor is a relatively complex equation and is computed on the flow sheet, I represent the average wellbore z-factor as the average of the well-bottom z-factor and well-head z-factor, taking those values from the flow sheet. In practice, z-factor is not exactly linear, but this is a better result than the old formula which left it off.
