### ISSUE TITLE
Heavy oil dilution M78

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#398]
Cell M78, Under the heavy oil dilution tab uses the following expression
IF(Known_API_diluent_or_dilbit="DILUENT",G68,IF(1-Fraction_diluent<=0.001,H68,(dilbit_bbl_per_day*H68-bitumen_bbl_per_day*E68)/diluent_bbl_per_day))

the bitumen_bbl_per_day is total volume of heavy oil and bitumen to be diluted
E68 is heavy oil energy density.

I don't think using E68 here is correct. Should consider the mass of bitumen and heavy oil and calculated the weighted average energy density.

Can heavy oil dilution deal with bitumen and heavy oil simultaneously?

**Comment by arbrandt** [comment]
Heavy oil dilution should be able to deal with diluting heavy oil as well as diluting bitumen. This equation says:

1. If I know the properties of the diluent (API), then use that to directly get the heating value.
2. If I know the properties only of the diluted crude or diluted bitumen (sometimes the case due to data availability), then take the properties of the diluted crude, the original crude (or bitumen) and use them to infer the properties of the diluent.

After looking at it again, I think it is doing the correct thing.
