### ISSUE TITLE
Crude oil storage solution GOR input condition and output condition issue

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#408]
In the crude oil storage tab, CellM40(solution GOR at input condition), CellM41(solution GOR at output condition) are only used in the CellM47 and CellM48. But M48 is not used.

**Comment by arbrandt** [comment]
We basically implemented two methods: one method uses the solution gas oil ratio esitmated by the Al-Shammasi correlation. That takes crude properties, temperature, pressure to estimate how much gas will be in solution. The other method uses some field measurements from the HARC tank study from Texas. For OPGEE 3.0 we decided to go to the empirical measurement rather than the correlation. If the user wants they can re-wire to use Al-Shammasi, so we leave it in the model for now.
