### ISSUE TITLE
Cumulative oil production vs EUR issues

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#414]
Cumulative oil production (cum_prod_oil) is not actually used by the model in calculations (except if Issue 410 is addressed). However, cum_prod_gas is used, which seems inconsistent. Adding to this, the EUR on the Drilling and Development sheet (M19) is calculated differently in OPGEE 3.0 such that it doesn't incorporate cum_prod_gas or cum_prod_oil. I think the same approach used for the EUR could be back applied to the oil and gas separately, perhaps with an option to still override them with user input on the secondary inputs sheet.

**Comment by arbrandt** [comment]
Fixed. I now do all EUR calculations based on an assumed lifetime of the field, as in the M19 approach. New secondary input called "years prod" is the number of estimated years of production at the current rate. Old method is left in there for someone to use in case they don't have a sense of the producing life of the field or in case they feel that the current production is highly atypical. For example, if current production is minimal and due to ramp quickly, extrapolating it for 30 years is probably not useful.
