### ISSUE TITLE
Error in equation for vented mining emissions

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#423]
On the Bitumen mining sheet, the mine face fugitives stream (Stream 281, Column L) is not multiplied by the molecular weight of the mine gas (M55) as it should be. This leads to mass flows in Stream 281 ~20x too low.

In addition, since mining fugitives here are calculated using VOR*Oil_prod, it seems potentially inappropriate to also apply the VOR to the post-flaring gas on the Venting sheet. Consider whether purposeful venting on the Venting sheet should be set to 0 for oil sands in light of this.

It may also be wise to create a mining-specific default VOR, perhaps in line with the emission factor for mining operations from OPGEE 2.0.

**Comment by arbrandt** [comment]
Agreed that an improved VOR that is oil sands specific makes sense. 

In order to make sure we are using best available data, I performed a lit search and found top-down data from airplane surveys in Baray et al. 2018. https://doi.org/10.5194/acp-18-7361-2018

Combining these data with production data from ST-39 in the month that their surveys were taken (raw bitumen production), we arrive at a production-weighted fugitive emissions rate of 22.9 scf/bbl. This is higher than OPGEE 2.0 factor, but not wildly so (3-4x). Scientifically, I much prefer top-down methods at this point, especially for wide area sources such as ponds and mines.

These calculations are now documented on the bitumen mining sheet. We no longer use the VOR for bitumen mining.
