### ISSUE TITLE
Add gas/CO2/sour gas injection wells to drilling module

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#424]
Drilling module currently accounts for production wells and water injection wells. Add other types of injection wells to the drilled well count, based on what kinds of injection technologies are in use on the field.

**Comment by arbrandt** [comment]
Yes, we do need to drill the number of injection wells for gas reinjection and gas flooding. Without detailed analysis of well counts in gas reinjection/gas flooding fields, we make an assumption that if gas reinjection or gas flooding are turned on, an additional count of wells equal to 1/4 the producing wells is added. This lower count is due to the fact that gas injection is typically "easier" than liquid production/injection due to the greater permeability of the reservoir to gas (gas flows much easier through rock). So we assume many fewer gas injection wells are needed than production wells. Future work could examine this in more detail.

**Comment by myjabbar** [comment]
In CO2 flood development,  90% of the current floods are WAG development where historical water injection wells are utilized to alternate water and CO2 slugs. The wells are **recompleted** prior the start of CO2 flood with corrosion resistant alloys and other measures  due to characteristics of supercritical CO2, e.g., corrosive, low temperature.
Not sure if the assumption of five spot pattern to assume CO2 injectors is helpful.
Moreover with the concept of increase CO2 utilization for future floods, horizontal CO2 injectors are utilized in a line drive pattern where the ratio of producers to injectors is 1:1.
