### ISSUE TITLE
Tank vapor to flaring not actually flared in model

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#425]
On the Secondary Inputs, the user can control the fraction of tanks with vapor recovery and the fraction using flare destruction. OPGEE generates two streams off of the tank based on these fractions. The recovery stream feeds back into the exported product, but the flaring stream (Stream 81) simply leaves the system without any emissions from the flaring process being accounted for.

Suggest tying this stream into the flaring sheet similar to how mine offgas flaring works. Ensure mass balance is maintained on the flow table following this correction.

**Comment by arbrandt** [comment]
Fixed. Good catch. The following things were done:
1. Stream 81 now goes into the flaring sheet.
2. The flaring fraction now applies just to the bulk separator gas sent to flare. The other two streams, mine flare gas and tank vapor flare gas, are now 100% flared. The mass balance is adjusted on the sheet so that it is computing the streams and their sums correctly.
3. The overall mass balance on the right of the flow table now correctly accounts for flaring by removing the separate summation of tank vapors to flare. Now it simply looks at the amount flared, which is equal to separator gas*flaring fraction+mine offgas flare+tank vapor flare.  Mass balance on flow table (full system mass balance) clears correctly.
