### ISSUE TITLE
Drilling fuel consumption in the Drilling&Development Tab

### ISSUE THREAD

**Issue by wennanlong** [arbrandt/OPGEE#466]
The formula of Drilling fuel consumption (M22) in the Drilling&Development Tab does not consider the fraction of vertical wells

Use the following formula

=Drilling_fuel_per_foot_vertical*(1-Fraction_wells_horizontal)*Field_depth*M8+Drilling_fuel_per_foot_horizontal*Fraction_wells_horizontal*Length_lateral*M8

**Comment by qlangfitt** [comment]
Is it because all wells have a vertical portion, and then it adds on energy for the horizontal portions for those wells which have one?

**Comment by arbrandt** [comment]
The drilling module uses a fixed factor per foot that applies to the whole well depth. Then for the lateral, it gives an "additional" energy use per foot in excess of the usual requirement. That is explained in the documentation. See also the RHS of the energy use tables in Secondary Inputs where it is listed as "gal additional diesel fuel per foot" rather than 
"gal diesel fuel per foot" for the first table.
