### ISSUE TITLE
Steam generation circular reference

### ISSUE THREAD

**Issue by arbrandt** [arbrandt/OPGEE#47]
For Yulia:

Steam generation inlet air enthalpy seems to be causing a circular reference which results in a #name error. See "Steam Generation" cell B229, which I moved over from the corresponding spot and replaced with a hard-coded "0" to get the model to work. Not sure why, but it seems that the circular ref was causing a "name" error.

**Comment by yuliachen** [comment]
Yes. It's fixed in the new steam sheet. 
The #Name error is caused by cell within a circle that contains a reference to a user defined function that isn't readily available. In this case, it's hard to have an if statement (cell D234 in steam sheet) within a circular calculation. 

For instant usage of the current steam sheet, deleting the if statement in cell D234 should work.

**Comment by yuliachen** [comment]
If deleting the if statement in cell D234 does not work, try this for D234:

=IFERROR(J233/M258-D229,0)

**Comment by arbrandt** [comment]
Appears to be fixed. Permenant fixes to steam sheet coming with Yulia updated sheet
