### ISSUE TITLE
Site method fugitives inclusive of reinjection compressors

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#86]
The site method fugitives sheet states that we assume the figures do not include gathering compressor, transmission compressor, storage compressor, or gas flooding compressor emissions. However, it does include "on-pad" compressor emissions. Which compressors are considered "on-pad"? Are the reinjection compressors on-pad? As an example, the CO2 reinjection compressor sheet calculates a fugitive rate using the compressor correlation on the site fugitives sheet, but the sour gas reinjection compressor lists 0. This leads me to believe that the CO2 reinjection compressor is considered "on-pad", but the sour gas reinjection compressor is not. If that's not the case, maybe we should go through the compressor sheets and make sure that for site method we are drawing in extra fugitives for off-pad and using 0 fugitives for on-pad. Maybe a simple list or table to identify which compressors we assume to fall into each category would be useful in the site method venting and fugitive emissions section of the documentation.

**Comment by JSRuthe** [comment]
I'm going to start with the following classification:

- Any equipment associated with enhanced oil recovery will be considered "off-pad". This will include compressors and wells used in sour gas, HC gas, and CO2 reinjection or flooding. Based on a quick scan of SPE literature (see, for example, [here](https://www.researchgate.net/publication/317293343_Optimizing_Injector-Producer_Spacing_for_CO2_Injection_in_Unconventional_Reservoirs_of_North_America)). spacing is in the hundreds of meters
- Any equipment associated with gas lift is "on-pad" since the gas is injected through casing tubing of the producer well

**Comment by JSRuthe** [comment]
I am considering adding a separate sheet for "VF - Secondary production practices", as fugitives from gas injection wells and compressors appear to fall outside of both our standard component-level and site-level models

**Comment by JSRuthe** [comment]
Completed today with 9a57298
