### ISSUE TITLE
Fuel cycle emissions and energy on electric gen and imports sheet have possible issues

### ISSUE THREAD

**Issue by qlangfitt** [arbrandt/OPGEE#87]
I'm having trouble wrapping my head around what's being calculated in the tables on the _Electricity Gen and Imports_ sheet at rows 102 to 123. If I understand correctly, the feedstock emissions (H106:H111) are the emissions resulting from  producing the feedstock (e.g., growing biomass, extracting natural gas, etc.) on a basis of emissions per electricity supplied to the user. This column's equations draw on emission factors for emissions per electricity generated from the feedstock. In my mind, the only adjustment that needs to be made after that is to divide by the transmission efficiency. There is a lot more going on than that in the equation. Why divide by the generation efficiency (i.e., efficiency of converting feedstock energy to electrical energy) if the emission factor is already in terms of generated electricity? On top of that, percentages are used, but not converted to fractional form. Finally, there are extra terms in the numerators ('Fuel Specs'!C400, 'Fuel Specs'!C406) that seem totally out of place. Same oddities exist in the energy feedstock column. Perhaps I'm misunderstanding - if so a brief explanation of what's going on in those cells would be really helpful.

Also, for my clarity, in the Energy half of the tables, does "feedstock" mean the mmbtu of energy inputs used to obtain the feedstock (e.g., fuel energy to drive tractors and produce fertilizer for biomass) per mmbtu of electricity supplied and does "fuel" mean the mmbtu energy content of the fuel consumed per mmbtu of electricity supplied?

**Comment by smasnadi** [comment]
Adam: I agree with CARB's comment.
- Why dividing by elec. generation efficiency? (this is already accounted in fuel cycle emissions numbers from GREET (table 4.3 of Fuel cycle sheet)
- I agree with CARB that we need a divide by the generation eff. But e.g. in cell H106 (elec gen sheet), the last parenthesis numerator and denominator are the same values.

**Comment by arbrandt** [comment]
I understand that this is confusing, but think that it is correct. I added the following note off to the right. It should explain the logic, I hope.


Notes:
--
If efficiencies are equal to GREET efficiencies (for power gen and grid)
then feedstock emissions are equal to those from the GREET model.
If the user adjusts the efficiency of generation or efficiency of grid, then
the GREET feedstock values must be adjusted for the difference.
This is because the GREET "feedstock" value for NG is the g/mmbtu
for producing gas, converted to per unit of gas-based power generation.
That is why gas "feedstock" emissions are ~29 g/MJ of power, because
you are roughly taking a GREET 15 g/MJ gas CI and using it in a 50%
efficient power generation source.
